Output lazycph.gif

Require lazycph

Set Shell zsh
Set Width 1200
Set Height 720
Set FontFamily "IosevkaTerm Nerd Font Mono"
Set FontSize 18
Set Padding 12

# Type a command in the terminal.
Type "lazycph ./addition.cpp"
Enter
Sleep 800ms

Tab
Type "60 7"
Tab
Type "67"
Ctrl+r
Sleep 2000ms

Tab 2
Sleep 300ms
Type "c"
Sleep 300ms
Tab

Type "1300 37"
Tab
Type "1338 (Wrong Answer)"
Ctrl+r
Sleep 2000ms

Hide
Type "rm -rf .lazycph"
Enter
